package cb.ext.dbs.constants;

public interface CompanyConstants {
	
	String DBS_COMPANY_INT_CODE = "DBS_COMPANY_INT_CODE";
	String DBS_COMPANY_FC_BATCH_CODE = "DBS_COMPANY_FC_BATCH_CODE";
	String DBS_COMPANY_RECONFILE_CODE = "DBS_C_RF";
	
	
	String DBS_COMPANY_DEBT_RESULT_DOCUMENTID  = "2355";
	
	
	int DBS_DEALER_DEBTFILE_ACCOUNT_TRNX_EXPLANATION     = 70537;
	int PERSONAL_DBS_DEALER_DEBTFILE_ACCOUNT_TRNX_EXPLANATION = 70539;
	int DBS_TRANSFER_DEALTER_TO_COMPANY_TRNX_EXPLANATION = 70598;
	int DBS_DEALER_TRANSFER_FROM_KTH_TRNX			     = 70599; 
	


}
