<service id="9600000350291080" serviceName="URN_PARTIALBACKDEPLOYTEST2_LIST_ALL_TABLES" serviceType="N" active="1" channelId="001" batch="0" batchType="" ortam="CB">
  <description>This name can be used.</description>
  <hasTableLock>0</hasTableLock>
  <reversalServiceOid></reversalServiceOid>
  <className></className>
  <tableName></tableName>
  <methodName>listAllTables</methodName>
  <scClassName>cb.tst.partialbackdeploytest2.bean.Services</scClassName>
  <target>0</target>
  <ttype>0</ttype>
  <visible>1</visible>
  <platform>1</platform>
  <componentId>9990000221059678</componentId>
  <componentCmsOid>9990000221059678</componentCmsOid>
  <componentCmsName>CB TST PartialBackDeployTest2</componentCmsName>
  <lastUpdated>1525457537169</lastUpdated>
</service>